import type { NextPage } from 'next'
import Head from 'next/head'

import LoginForm from '@/modules/auth/components/login-form'

import styles from '@/styles/pages/home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginForm />
      </main>
    </div>
  )
}

export default Home
