import type { NextPage } from 'next'
import Head from 'next/head'

import { Button } from '@components/index'

import styles from '@styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button size="sm">Example Button</Button>
        <br />
        <Button size="md">Example Button</Button>
        <br />
        <Button size="md" block>
          Example Button
        </Button>
        <br />
        <Button size="sm" theme="secondary">
          Example Button
        </Button>
        <br />
        <Button size="md" theme="secondary">
          Example Button
        </Button>
        <br />
      </main>
    </div>
  )
}

export default Home
